now works for Graphviz 2.4.  Still has some problems w/ not fully connected graphs on neato under 2.4
git-svn-id: file:///home/git/hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/Rgraphviz@13371 bc3139a8-67e5-0310-9ffc-ced21a209358

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -272,7 +272,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="src/Rgraphviz.c"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS DOTNEATO_CONFIG GVIZ_DEFS PKG_CPPFLAGS PKG_LIBS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS DOTNEATO_CONFIG PKG_CONFIG GVIZ_DEFS PKG_CPPFLAGS PKG_LIBS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1295,11 +1295,59 @@ echo "$as_me: error: please specify a valid path to
            fi
 	fi
 else
+	if test -z "${PKG_CONFIG}" ; then
+		# Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+
+if test -n "$PKG_CONFIG"; then
+  echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
+echo "${ECHO_T}$PKG_CONFIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+	fi
+	if test -z "${PKG_CONFIG}" ; then
      echo "$as_me:$LINENO: result: failed" >&5
 echo "${ECHO_T}failed" >&6
-     { { echo "$as_me:$LINENO: error: please specify a valid path to 'dotneato-config' version >= 1.12 using --with-graphviz=DIR" >&5
-echo "$as_me: error: please specify a valid path to 'dotneato-config' version >= 1.12 using --with-graphviz=DIR" >&2;}
-   { (exit 1); exit 1; }; }
+     { { echo "$as_me:$LINENO: error: please specify a valid path to 'dotneato-config' version >= 1.12 or 'pkg-config' if you have graphviz >= 2.4" >&5
+echo "$as_me: error: please specify a valid path to 'dotneato-config' version >= 1.12 or 'pkg-config' if you have graphviz >= 2.4" >&2;}
+   { (exit using --with-graphviz=DIR); exit using --with-graphviz=DIR; }; }
+	 exit 1
+	fi
+	GVIZ_DEFS="-DGRAPHVIZGT_2_4"
+	GRAPHVIZ_CONFIG="$PKG_CONFIG libgvc"
+	PKG_CPPFLAGS="`${GRAPHVIZ_CONFIG} --cflags`"
+	PKG_LIBS="`${GRAPHVIZ_CONFIG} --libs`"
 fi
 
 
@@ -1940,6 +1988,7 @@ s,@ECHO_N@,$ECHO_N,;t t
 s,@ECHO_T@,$ECHO_T,;t t
 s,@LIBS@,$LIBS,;t t
 s,@DOTNEATO_CONFIG@,$DOTNEATO_CONFIG,;t t
+s,@PKG_CONFIG@,$PKG_CONFIG,;t t
 s,@GVIZ_DEFS@,$GVIZ_DEFS,;t t
 s,@PKG_CPPFLAGS@,$PKG_CPPFLAGS,;t t
 s,@PKG_LIBS@,$PKG_LIBS,;t t
