Major refactoring of configure.in and configure (turns out that configure had not been updated despite configure.in being updated earlier. Hopefully this works, but has not been tested with a pkg-config installation. Fixed an example in agopenSimple.Rd
git-svn-id: file:///home/git/hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/Rgraphviz@37861 bc3139a8-67e5-0310-9ffc-ced21a209358

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -651,8 +651,6 @@ LIBS
 build_alias
 host_alias
 target_alias
-PKG_CONFIG
-DOTNEATO_CONFIG
 CC
 CFLAGS
 LDFLAGS
@@ -663,6 +661,8 @@ OBJEXT
 CPP
 GREP
 EGREP
+PKG_CONFIG
+DOTNEATO_CONFIG
 GVIZ_DEFS
 PKG_CPPFLAGS
 PKG_LIBS
@@ -1249,7 +1249,7 @@ if test -n "$ac_init_help"; then
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
-  --with-graphviz=DIR     root directory of graphviz installation (defaults to
+  --with-graphviz=DIR     root directory of Graphviz installation (defaults to
                           /usr/local)
 
 Some influential environment variables:
@@ -1694,208 +1694,6 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-
-# Check whether --with-graphviz was given.
-if test "${with_graphviz+set}" = set; then
-  withval=$with_graphviz; if test ${with_graphviz} = "yes"; then
-             GRAPHVIZ_DIR='/usr/local'
-           else
-             GRAPHVIZ_DIR=${with_graphviz}
-           fi
-else
-  GRAPHVIZ_DIR=""
-fi
-
-
-GRAPHVIZ_DEFAULT_DIR=""
-if test -z "${GRAPHVIZ_DIR}" ; then
-   { echo "$as_me:$LINENO: No --with-graphviz option was specified. Trying to find graphviz using other methods." >&5
-echo "$as_me: No --with-graphviz option was specified. Trying to find graphviz using other methods." >&6;}
-   if test -z "${PKG_CONFIG}" ; then
-      # Extract the first word of "pkg-config", so it can be a program name with args.
-set dummy pkg-config; ac_word=$2
-{ echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  case $PKG_CONFIG in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-IFS=$as_save_IFS
-
-  ;;
-esac
-fi
-PKG_CONFIG=$ac_cv_path_PKG_CONFIG
-if test -n "$PKG_CONFIG"; then
-  { echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
-echo "${ECHO_T}$PKG_CONFIG" >&6; }
-else
-  { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-fi
-
-
-   fi
-   if ! test -z "${PKG_CONFIG}" ; then
-      GRAPHVIZ_CONFIG="$PKG_CONFIG libgvc"
-      GRAPHVIZ_VERSTR="`${GRAPHVIZ_CONFIG} --modversion || echo ''`"
-      if test -z "${GRAPHVIZ_VERSTR}" ; then
-         { echo "$as_me:$LINENO: pkg-config was not able to find the graphviz library libgvc. This either indicates that graphviz is old or that something is wrong. Verify graphviz is installed and that PKG_CONFIG_PATH is correct." >&5
-echo "$as_me: pkg-config was not able to find the graphviz library libgvc. This either indicates that graphviz is old or that something is wrong. Verify graphviz is installed and that PKG_CONFIG_PATH is correct." >&6;}
-      else
-         PKG_CPPFLAGS="`${GRAPHVIZ_CONFIG} --cflags`"
-         PKG_LIBS="`${GRAPHVIZ_CONFIG} --libs`"
-      fi
-   fi
-
-   if test -z "${GRAPHVIZ_VERSTR}" ; then
-      { echo "$as_me:$LINENO: Using dotneato-config to find graphviz" >&5
-echo "$as_me: Using dotneato-config to find graphviz" >&6;}
-      if test -z "${DOTNEATO_CONFIG}" ; then
-         # Extract the first word of "dotneato-config", so it can be a program name with args.
-set dummy dotneato-config; ac_word=$2
-{ echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_DOTNEATO_CONFIG+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  case $DOTNEATO_CONFIG in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_DOTNEATO_CONFIG="$DOTNEATO_CONFIG" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_DOTNEATO_CONFIG="$as_dir/$ac_word$ac_exec_ext"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-IFS=$as_save_IFS
-
-  ;;
-esac
-fi
-DOTNEATO_CONFIG=$ac_cv_path_DOTNEATO_CONFIG
-if test -n "$DOTNEATO_CONFIG"; then
-  { echo "$as_me:$LINENO: result: $DOTNEATO_CONFIG" >&5
-echo "${ECHO_T}$DOTNEATO_CONFIG" >&6; }
-else
-  { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-fi
-
-
-      fi
-      if test -z "${DOTNEATO_CONFIG}" ; then
-         { echo "$as_me:$LINENO: dotneato-config not found in PATH." >&5
-echo "$as_me: dotneato-config not found in PATH." >&6;}
-         GRAPHVIZ_DEFAULT_DIR="/usr/local"
-      else
-         GRAPHVIZ_VERSTR=`${DOTNEATO_CONFIG} --version`
-         PKG_CPPFLAGS="`${DOTNEATO_CONFIG} --cflags`"
-         PKG_LIBS="`${DOTNEATO_CONFIG} --ldflags` `${DOTNEATO_CONFIG} --libs` -lm"
-      fi
-   fi
-fi
-
-if ! test -z "${GRAPHVIZ_DEFAULT_DIR}" ; then
-   { echo "$as_me:$LINENO: Trying default graphviz dir ${GRAPHVIZ_DEFAULT_DIR}.  Consider specifying --with-graphviz" >&5
-echo "$as_me: Trying default graphviz dir ${GRAPHVIZ_DEFAULT_DIR}.  Consider specifying --with-graphviz" >&6;}
-   GRAPHVIZ_DIR=${GRAPHVIZ_DEFAULT_DIR}
-fi
-if ! test -z "${GRAPHVIZ_DIR}"; then
-    if test -z "${GRAPHVIZ_DEFAULT_DIR}" ; then
-                { echo "$as_me:$LINENO: Using user specified graphviz root directory ${GRAPHVIZ_DIR}" >&5
-echo "$as_me: Using user specified graphviz root directory ${GRAPHVIZ_DIR}" >&6;}
-    else
-        { echo "$as_me:$LINENO: Using graphviz root directory ${GRAPHVIZ_DIR}" >&5
-echo "$as_me: Using graphviz root directory ${GRAPHVIZ_DIR}" >&6;}
-    fi
-    DOT="${GRAPHVIZ_DIR}/bin/dot"
-    if ! test -x "${DOT}" ; then
-       { { echo "$as_me:$LINENO: error: $DOT not found.  Check graphviz installation." >&5
-echo "$as_me: error: $DOT not found.  Check graphviz installation." >&2;}
-   { (exit 1); exit 1; }; }
-    else
-       GRAPHVIZ_VERSTR=`${DOT} -V 2>&1 | cut -f3 -d" "`
-                     if test "${GRAPHVIZ_VERSTR}" = "Graphviz"; then
-                  GRAPHVIZ_VERSTR=`${DOT} -V 2>&1 | cut -f5 -d" "`
-       fi
-       if test "${GRAPHVIZ_VERSTR}" = "graphviz"; then
-                  GRAPHVIZ_VERSTR=`${DOT} -V 2>&1 | cut -f5 -d" "`
-       fi
-                            MAJOR=`echo ${GRAPHVIZ_VERSTR} | cut -f1 -d"."`
-       MINOR=`echo ${GRAPHVIZ_VERSTR} | cut -f2 -d"."`
-       if (test ${MAJOR} -eq "2" && test ${MINOR} -le "2") ; then
-         PKG_CPPFLAGS="-I${GRAPHVIZ_DIR}/include/graphviz"
-         PKG_LIBS="-L${GRAPHVIZ_DIR}/lib/graphviz -ldotneato -lm"
-       else
-         PKG_CPPFLAGS="-I${GRAPHVIZ_DIR}/include/graphviz"
-         PKG_LIBS="-L${GRAPHVIZ_DIR}/lib/graphviz -L${GRAPHVIZ_DIR}/lib -lgvc"
-       fi
-    fi
-fi
-
-if test -z "${GRAPHVIZ_VERSTR}" ; then
-   { { echo "$as_me:$LINENO: error: graphviz was not found." >&5
-echo "$as_me: error: graphviz was not found." >&2;}
-   { (exit 1); exit 1; }; }
-   exit 1
-fi
-
-{ echo "$as_me:$LINENO: Found Graphviz version $GRAPHVIZ_VERSTR" >&5
-echo "$as_me: Found Graphviz version $GRAPHVIZ_VERSTR" >&6;}
-{ echo "$as_me:$LINENO: Corresponding to major version $MAJOR and minor version $MINOR" >&5
-echo "$as_me: Corresponding to major version $MAJOR and minor version $MINOR" >&6;}
-
-if (test ${MAJOR} -lt "2") || (test ${MAJOR} -eq "2" && test ${MINOR} -lt "2") ; then
-   { { echo "$as_me:$LINENO: error: \"Need graphviz >= 2.2\"" >&5
-echo "$as_me: error: \"Need graphviz >= 2.2\"" >&2;}
-   { (exit 1); exit 1; }; }
-   exit 1
-fi
-
-ac_config_files="$ac_config_files R/graphviz_build_version.R"
-
-GRAPHVIZ_BUILD_VERSION=${GRAPHVIZ_VERSTR}
-{ echo "$as_me:$LINENO: Build Version = $GRAPHVIZ_BUILD_VERSION" >&5
-echo "$as_me: Build Version = $GRAPHVIZ_BUILD_VERSION" >&6;}
-
-{ echo "$as_me:$LINENO: We have inferred the following flags for graphviz" >&5
-echo "$as_me: We have inferred the following flags for graphviz" >&6;}
-{ echo "$as_me:$LINENO: ..PKG_CPPFLAGS=${PKG_CPPFLAGS}" >&5
-echo "$as_me: ..PKG_CPPFLAGS=${PKG_CPPFLAGS}" >&6;}
-{ echo "$as_me:$LINENO: ..PKG_LIBS=${PKG_LIBS}" >&5
-echo "$as_me: ..PKG_LIBS=${PKG_LIBS}" >&6;}
-
-GVIZ_DEFS=" -DGRAPHVIZ_MAJOR=${MAJOR} -DGRAPHVIZ_MINOR=${MINOR} "
-
-{ echo "$as_me:$LINENO: checking for whether compiler has bool" >&5
-echo $ECHO_N "checking for whether compiler has bool... $ECHO_C" >&6; }
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -3638,6 +3436,8 @@ _ACEOF
 
 fi
 
+{ echo "$as_me:$LINENO: checking for whether compiler has bool" >&5
+echo $ECHO_N "checking for whether compiler has bool... $ECHO_C" >&6; }
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -3691,6 +3491,205 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
+
+# Check whether --with-graphviz was given.
+if test "${with_graphviz+set}" = set; then
+  withval=$with_graphviz; if test ${with_graphviz} = "yes"; then
+             GRAPHVIZ_DIR='/usr/local'
+           else
+             GRAPHVIZ_DIR=${with_graphviz}
+           fi
+else
+  GRAPHVIZ_DIR=""
+fi
+
+
+
+if test -z "${GRAPHVIZ_DIR}" ; then
+   { echo "$as_me:$LINENO: No --with-graphviz option was specified. Trying to find Graphviz using other methods." >&5
+echo "$as_me: No --with-graphviz option was specified. Trying to find Graphviz using other methods." >&6;}
+      if test -z "${PKG_CONFIG}" ; then
+      # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+if test -n "$PKG_CONFIG"; then
+  { echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
+echo "${ECHO_T}$PKG_CONFIG" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+   fi
+   if ! test -z "${PKG_CONFIG}" ; then
+      GRAPHVIZ_CONFIG="${PKG_CONFIG} libgvc"
+      GRAPHVIZ_VERSTR="`${GRAPHVIZ_CONFIG} --modversion || echo ''`"
+      if test -z "${GRAPHVIZ_VERSTR}" ; then
+         { echo "$as_me:$LINENO: pkg-config was not able to find the Graphviz library libgvc. This either indicates that Graphviz is old or that something is wrong. Verify Graphviz is installed and that PKG_CONFIG_PATH is correct." >&5
+echo "$as_me: pkg-config was not able to find the Graphviz library libgvc. This either indicates that Graphviz is old or that something is wrong. Verify Graphviz is installed and that PKG_CONFIG_PATH is correct." >&6;}
+      else
+         PKG_CPPFLAGS="`${GRAPHVIZ_CONFIG} --cflags`"
+         PKG_LIBS="`${GRAPHVIZ_CONFIG} --libs`"
+      fi
+   fi
+         if test -z "${GRAPHVIZ_VERSTR}" ; then
+      if test -z "${DOTNEATO_CONFIG}" ; then
+         # Extract the first word of "dotneato-config", so it can be a program name with args.
+set dummy dotneato-config; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_DOTNEATO_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $DOTNEATO_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_DOTNEATO_CONFIG="$DOTNEATO_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_DOTNEATO_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+DOTNEATO_CONFIG=$ac_cv_path_DOTNEATO_CONFIG
+if test -n "$DOTNEATO_CONFIG"; then
+  { echo "$as_me:$LINENO: result: $DOTNEATO_CONFIG" >&5
+echo "${ECHO_T}$DOTNEATO_CONFIG" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+      fi
+      if test -z "${DOTNEATO_CONFIG}" ; then
+         { echo "$as_me:$LINENO: dotneato-config not found in PATH." >&5
+echo "$as_me: dotneato-config not found in PATH." >&6;}
+	 { echo "$as_me:$LINENO: Using default directory /usr/local, consider specifiying --with-graphviz" >&5
+echo "$as_me: Using default directory /usr/local, consider specifiying --with-graphviz" >&6;}
+         GRAPHVIZ_DIR="/usr/local"
+      else
+         GRAPHVIZ_VERSTR=`${DOTNEATO_CONFIG} --version`
+         PKG_CPPFLAGS="`${DOTNEATO_CONFIG} --cflags`"
+         PKG_LIBS="`${DOTNEATO_CONFIG} --ldflags` `${DOTNEATO_CONFIG} --libs` -lm"
+      fi
+   fi
+else
+   { echo "$as_me:$LINENO: Using Graphviz dir '${GRAPHVIZ_DIR}'" >&5
+echo "$as_me: Using Graphviz dir '${GRAPHVIZ_DIR}'" >&6;}
+fi
+
+
+if test -z "${GRAPHVIZ_VERSTR}" ; then
+   DOT="${GRAPHVIZ_DIR}/bin/dot"
+   if ! test -x "${DOT}" ; then
+      { { echo "$as_me:$LINENO: error: $DOT not found.  Check Graphviz installation." >&5
+echo "$as_me: error: $DOT not found.  Check Graphviz installation." >&2;}
+   { (exit 1); exit 1; }; }
+      exit 1
+   else
+      GRAPHVIZ_VERSTR=`${DOT} -V 2>&1 | cut -f3 -d" "`
+            if test "${GRAPHVIZ_VERSTR}" = "Graphviz"; then
+         GRAPHVIZ_VERSTR=`${DOT} -V 2>&1 | cut -f5 -d" "`
+      fi
+      if test "${GRAPHVIZ_VERSTR}" = "graphviz"; then
+         GRAPHVIZ_VERSTR=`${DOT} -V 2>&1 | cut -f5 -d" "`
+      fi
+   fi
+fi
+
+
+if test -z ${GRAPHVIZ_VERSTR} ; then
+    { { echo "$as_me:$LINENO: error: Unable to determine Graphviz version. Report to Rgraphviz maintainer." >&5
+echo "$as_me: error: Unable to determine Graphviz version. Report to Rgraphviz maintainer." >&2;}
+   { (exit 1); exit 1; }; }
+    exit 1
+fi
+
+{ echo "$as_me:$LINENO: Found Graphviz version '${GRAPHVIZ_VERSTR}'." >&5
+echo "$as_me: Found Graphviz version '${GRAPHVIZ_VERSTR}'." >&6;}
+
+MAJOR=`echo ${GRAPHVIZ_VERSTR} | cut -f1 -d"."`
+MINOR=`echo ${GRAPHVIZ_VERSTR} | cut -f2 -d"."`
+if test -z ${MAJOR} || test -z ${MINOR} ; then
+   { { echo "$as_me:$LINENO: error: Unable to infer Graphviz major and minor version, report to Rgraphviz maintainer" >&5
+echo "$as_me: error: Unable to infer Graphviz major and minor version, report to Rgraphviz maintainer" >&2;}
+   { (exit 1); exit 1; }; }
+   exit 1
+fi
+{ echo "$as_me:$LINENO: Graphviz major version is '${MAJOR}' and minor version is '${MINOR}'." >&5
+echo "$as_me: Graphviz major version is '${MAJOR}' and minor version is '${MINOR}'." >&6;}
+if (test ${MAJOR} -lt "2") || (test ${MAJOR} -eq "2" && test ${MINOR} -lt "2") ; then
+   { { echo "$as_me:$LINENO: error: Need Graphviz >= 2.2" >&5
+echo "$as_me: error: Need Graphviz >= 2.2" >&2;}
+   { (exit 1); exit 1; }; }
+   exit 1
+fi
+
+if (test ${MAJOR} -eq "2" && test ${MINOR} -le "2") ; then
+   PKG_CPPFLAGS="-I${GRAPHVIZ_DIR}/include/graphviz"
+   PKG_LIBS="-L${GRAPHVIZ_DIR}/lib/graphviz -ldotneato -lm"
+else
+   PKG_CPPFLAGS="-I${GRAPHVIZ_DIR}/include/graphviz"
+   PKG_LIBS="-L${GRAPHVIZ_DIR}/lib/graphviz -L${GRAPHVIZ_DIR}/lib -lgvc"
+fi
+{ echo "$as_me:$LINENO: Using the following compilation and linking flags for Rgraphviz" >&5
+echo "$as_me: Using the following compilation and linking flags for Rgraphviz" >&6;}
+{ echo "$as_me:$LINENO:    PKG_CPPFLAGS=${PKG_CPPFLAGS}" >&5
+echo "$as_me:    PKG_CPPFLAGS=${PKG_CPPFLAGS}" >&6;}
+{ echo "$as_me:$LINENO:    PKG_LIBS=${PKG_LIBS}" >&5
+echo "$as_me:    PKG_LIBS=${PKG_LIBS}" >&6;}
+
+ac_config_files="$ac_config_files R/graphviz_build_version.R"
+
+GRAPHVIZ_BUILD_VERSION=${GRAPHVIZ_VERSTR}
+{ echo "$as_me:$LINENO: Setting Graphviz Build version to '${GRAPHVIZ_BUILD_VERSION}'." >&5
+echo "$as_me: Setting Graphviz Build version to '${GRAPHVIZ_BUILD_VERSION}'." >&6;}
+
+GVIZ_DEFS="${GVIZ_DEFS} -DGRAPHVIZ_MAJOR=${MAJOR} -DGRAPHVIZ_MINOR=${MINOR} "
 
 
 
@@ -4364,8 +4363,6 @@ LIBS!$LIBS$ac_delim
 build_alias!$build_alias$ac_delim
 host_alias!$host_alias$ac_delim
 target_alias!$target_alias$ac_delim
-PKG_CONFIG!$PKG_CONFIG$ac_delim
-DOTNEATO_CONFIG!$DOTNEATO_CONFIG$ac_delim
 CC!$CC$ac_delim
 CFLAGS!$CFLAGS$ac_delim
 LDFLAGS!$LDFLAGS$ac_delim
@@ -4376,6 +4373,8 @@ OBJEXT!$OBJEXT$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
+PKG_CONFIG!$PKG_CONFIG$ac_delim
+DOTNEATO_CONFIG!$DOTNEATO_CONFIG$ac_delim
 GVIZ_DEFS!$GVIZ_DEFS$ac_delim
 PKG_CPPFLAGS!$PKG_CPPFLAGS$ac_delim
 PKG_LIBS!$PKG_LIBS$ac_delim
