fixes
git-svn-id: https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/Rgraphviz@9009 bc3139a8-67e5-0310-9ffc-ced21a209358

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -902,18 +902,14 @@ echo $ECHO_N "checking for graphviz... $ECHO_C" >&6
 if test "${with_graphviz+set}" = set; then
   withval="$with_graphviz"
   if test x"$withval" != no ; then
-	echo "$as_me:905: result: yes" >&5
-echo "${ECHO_T}yes" >&6
 	DOTNEATO_CONFIG="$withval"
  else
-	echo "$as_me:909: result: no" >&5
-echo "${ECHO_T}no" >&6
 	DOTNEATO_CONFIG="not found"
  fi
 else
   # Extract the first word of "dotneato-config", so it can be a program name with args.
 set dummy dotneato-config; ac_word=$2
-echo "$as_me:916: checking for $ac_word" >&5
+echo "$as_me:912: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_DOTNEATO_CONFIG+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -930,7 +926,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_DOTNEATO_CONFIG="$ac_dir/$ac_word"
-   echo "$as_me:933: found $ac_dir/$ac_word" >&5
+   echo "$as_me:929: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -942,16 +938,18 @@ fi
 DOTNEATO_CONFIG=$ac_cv_path_DOTNEATO_CONFIG
 
 if test -n "$DOTNEATO_CONFIG"; then
-  echo "$as_me:945: result: $DOTNEATO_CONFIG" >&5
+  echo "$as_me:941: result: $DOTNEATO_CONFIG" >&5
 echo "${ECHO_T}$DOTNEATO_CONFIG" >&6
 else
-  echo "$as_me:948: result: no" >&5
+  echo "$as_me:944: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 fi;
 
 if test ${DOTNEATO_CONFIG} != "not found"; then
+	echo "$as_me:951: result: ${DOTNEATO_CONFIG}" >&5
+echo "${ECHO_T}${DOTNEATO_CONFIG}" >&6
 	PKG_LIBS="-Wl `${DOTNEATO_CONFIG} --libs` -lm"
 	PKG_CPPFLAGS="`${DOTNEATO_CONFIG} --cflags`"
 
@@ -967,9 +965,9 @@ if test ${DOTNEATO_CONFIG} != "not found"; then
 	   fi
 	fi
 else
-     echo "$as_me:970: result: failed" >&5
+     echo "$as_me:968: result: failed" >&5
 echo "${ECHO_T}failed" >&6
-     { { echo "$as_me:972: error: please specify a valid path to 'dotneato-config' with --with-graphviz=DIR" >&5
+     { { echo "$as_me:970: error: please specify a valid path to 'dotneato-config' with --with-graphviz=DIR" >&5
 echo "$as_me: error: please specify a valid path to 'dotneato-config' with --with-graphviz=DIR" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -1084,7 +1082,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1087: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1085: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1251,7 +1249,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1254: error: ambiguous option: $1
+    { { echo "$as_me:1252: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1270,7 +1268,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1273: error: unrecognized option: $1
+  -*) { { echo "$as_me:1271: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1306,7 +1304,7 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "src/Makevars" ) CONFIG_FILES="$CONFIG_FILES src/Makevars" ;;
-  *) { { echo "$as_me:1309: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:1307: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1499,7 +1497,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1502: creating $ac_file" >&5
+    { echo "$as_me:1500: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1517,7 +1515,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1520: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1518: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1530,7 +1528,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1533: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1531: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
