one more update
git-svn-id: https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/Rgraphviz@9016 bc3139a8-67e5-0310-9ffc-ced21a209358

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -963,12 +963,25 @@ echo "${ECHO_T}${DOTNEATO_CONFIG}" >&6
 	   if test ${MINOR} -eq "12"; then
 		GVIZ_DEFS="-DGRAPHVIZ_1_12"
 	   fi
+	   if test ${MINOR} -lt "12"; then
+		echo "$as_me:967: result: failed" >&5
+echo "${ECHO_T}failed" >&6
+		{ { echo "$as_me:969: error: please specify a valid path to 'dotneato-config' version >= 1.12 using --with-graphviz=DIR" >&5
+echo "$as_me: error: please specify a valid path to 'dotneato-config' version >= 1.12 using --with-graphviz=DIR" >&2;}
+   { (exit 1); exit 1; }; }
+	   fi
+	else
+	     echo "$as_me:974: result: failed" >&5
+echo "${ECHO_T}failed" >&6
+     	     { { echo "$as_me:976: error: please specify a valid path to 'dotneato-config' version >= 1.12 using --with-graphviz=DIR" >&5
+echo "$as_me: error: please specify a valid path to 'dotneato-config' version >= 1.12 using --with-graphviz=DIR" >&2;}
+   { (exit 1); exit 1; }; }
 	fi
 else
-     echo "$as_me:968: result: failed" >&5
+     echo "$as_me:981: result: failed" >&5
 echo "${ECHO_T}failed" >&6
-     { { echo "$as_me:970: error: please specify a valid path to 'dotneato-config' with --with-graphviz=DIR" >&5
-echo "$as_me: error: please specify a valid path to 'dotneato-config' with --with-graphviz=DIR" >&2;}
+     { { echo "$as_me:983: error: please specify a valid path to 'dotneato-config' version >= 1.12 using --with-graphviz=DIR" >&5
+echo "$as_me: error: please specify a valid path to 'dotneato-config' version >= 1.12 using --with-graphviz=DIR" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -1082,7 +1095,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1085: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1098: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1249,7 +1262,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1252: error: ambiguous option: $1
+    { { echo "$as_me:1265: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1268,7 +1281,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1271: error: unrecognized option: $1
+  -*) { { echo "$as_me:1284: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1304,7 +1317,7 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "src/Makevars" ) CONFIG_FILES="$CONFIG_FILES src/Makevars" ;;
-  *) { { echo "$as_me:1307: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:1320: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1497,7 +1510,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1500: creating $ac_file" >&5
+    { echo "$as_me:1513: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1515,7 +1528,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1518: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1531: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1528,7 +1541,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1531: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1544: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
