update the configure script
git-svn-id: file:///home/git/hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/Rgraphviz@9006 bc3139a8-67e5-0310-9ffc-ced21a209358

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.4 .
+# From configure.in Revision: 1.6 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52.
 #
@@ -913,20 +913,21 @@ for ac_dir in $ac_dummy; do
 fi
 done
 
+  test -z "$ac_cv_path_DOTNEATO_CONFIG" && ac_cv_path_DOTNEATO_CONFIG=""NO_PROG""
   ;;
 esac
 fi
 DOTNEATO_CONFIG=$ac_cv_path_DOTNEATO_CONFIG
 
 if test -n "$DOTNEATO_CONFIG"; then
-  echo "$as_me:922: result: $DOTNEATO_CONFIG" >&5
+  echo "$as_me:923: result: $DOTNEATO_CONFIG" >&5
 echo "${ECHO_T}$DOTNEATO_CONFIG" >&6
 else
-  echo "$as_me:925: result: no" >&5
+  echo "$as_me:926: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
-if test -n "${DOTNEATO_CONFIG}"; then
+if test ${DOTNEATO_CONFIG} != "NO_PROG"; then
 	PKG_LIBS="-Wl `${DOTNEATO_CONFIG} --libs` -lm"
 	PKG_CPPFLAGS="`${DOTNEATO_CONFIG} --cflags`"
 
@@ -941,6 +942,12 @@ if test -n "${DOTNEATO_CONFIG}"; then
 		GVIZ_DEFS="-DGRAPHVIZ_1_12"
 	   fi
 	fi
+else
+   echo "$as_me:946: result: failed" >&5
+echo "${ECHO_T}failed" >&6
+   { { echo "$as_me:948: error: please specify a valid path to 'dotneato-config' with --with-graphviz=DIR" >&5
+echo "$as_me: error: please specify a valid path to 'dotneato-config' with --with-graphviz=DIR" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 ac_config_files="$ac_config_files src/Makevars"
@@ -1053,7 +1060,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1056: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1063: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1220,7 +1227,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1223: error: ambiguous option: $1
+    { { echo "$as_me:1230: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1239,7 +1246,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1242: error: unrecognized option: $1
+  -*) { { echo "$as_me:1249: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1275,7 +1282,7 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "src/Makevars" ) CONFIG_FILES="$CONFIG_FILES src/Makevars" ;;
-  *) { { echo "$as_me:1278: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:1285: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1468,7 +1475,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1471: creating $ac_file" >&5
+    { echo "$as_me:1478: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1486,7 +1493,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1489: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1496: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1499,7 +1506,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1502: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1509: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
